### PR TITLE
added planned outage for server update and rebooting

### PR DESCRIPTION
**Pull request by iamyaash**
https://pagure.io/fedora-infrastructure/issue/12293
created planned outage for **Server update/reboots**

### CODE REVIEW

**Comment by nirik** [comment]
Looks pretty good, but can you update the title?

Something like "Server updates and reboots" ?

**Comment by iamyaash** [comment]
> Looks pretty good, but can you update the title?
> 
> Something like "Server updates and reboots" ?

yeah sure!

**Comment by iamyaash** [comment]
@nirik I have updated the title.

> my bad, I have changed username recently. so i ended up changing branches and created new outage, but forgot to change the title. I'll make not to make this mistake again!

**Comment by nirik** [comment]
No problem at all. Thanks for the pr!

**Pull request merged**
